
INSERT INTO role(role_id,name,movie_id) VALUES('1','Batman','1');
INSERT INTO role(role_id,name,movie_id) VALUES('2','Superman','1');
INSERT INTO role(role_id,name,movie_id) VALUES('3','Lois','1');
INSERT INTO role(role_id,name,movie_id) VALUES('4','Iron Man','2');
INSERT INTO role(role_id,name,movie_id) VALUES('5','Black Widow','2');
INSERT INTO role(role_id,name,movie_id) VALUES('6','Captain America','2');
INSERT INTO role(role_id,name,movie_id) VALUES('7','Mystique','4');
INSERT INTO role(role_id,name,movie_id) VALUES('8','Judy Hopps','5');
INSERT INTO role(role_id,name,movie_id) VALUES('9','Tris','6');
INSERT INTO role(role_id,name,movie_id) VALUES('10','Four','6');
INSERT INTO role(role_id,name,movie_id) VALUES('11','Monkey','9');
INSERT INTO role(role_id,name,movie_id) VALUES('12','Po','9');
INSERT INTO role(role_id,name,movie_id) VALUES('13','J.Daniel Altas','12');
INSERT INTO role(role_id,name,movie_id) VALUES('14','Li','12');
INSERT INTO role(role_id,name,movie_id) VALUES('15','Jason Bourne','16');
INSERT INTO role(role_id,name,movie_id) VALUES('16','Cooper','21');
INSERT INTO role(role_id,name,movie_id) VALUES('17','Cobb','33');
INSERT INTO role(role_id,name,movie_id) VALUES('18','Han solo','34');
INSERT INTO role(role_id,name,movie_id) VALUES('19','Chanchad','25');
INSERT INTO role(role_id,name,movie_id) VALUES('20','Wolverine','38');
INSERT INTO role(role_id,name,movie_id) VALUES('21','Beast','38');
INSERT INTO role(role_id,name,movie_id) VALUES('22','Professor Charles Xavier','38');
INSERT INTO role(role_id,name,movie_id) VALUES('22','Erik Lehnsherr','38');
INSERT INTO role(role_id,name,movie_id) VALUES('23','Neo','36');
INSERT INTO role(role_id,name,movie_id) VALUES('24','Caleb','6');
INSERT INTO role(role_id,name,movie_id) VALUES('25','Magic','51');
INSERT INTO role(role_id,name,movie_id) VALUES('26','Granger','44');
INSERT INTO role(role_id,name,movie_id) VALUES('27','Harry Potter','45');